export const enum VISTAS_DOCENTE {

  PERFIL = 'AMD_PERFIL',
  PERFIL_PIN = 'AMD_PERFIL_PIN',
  PERFIL_FOTO = 'AMD_PERFIL_FOTO',
  PERFIL_DATOS = 'AMD_PERFIL_DATOS',
  PERFIL_MODO_OSCURO = 'AMD_PERFIL_MODO_OSCURO',

  NOTIFICACIONES = 'AMD_NOTIFICACIONES',

  AAI = 'AMD_AAI',
  MAIL = 'AMD_MAIL',
  TEAMS = 'AMD_TEAMS',
  MENSAJES_SECCIONES = 'AMD_MENSAJES_SECCIONES',
  ENVIA_MENSAJE_SECCIONES = 'AMD_ENVIA_MENSAJE_SECCIONES',
  CONTACTOS_SEDES = 'AMD_CONTACTOS_SEDES',
  PRINCIPAL = 'AMD_PRINCIPAL',
  BUZON_OPINIONES = 'AMD_BUZON_OPINIONES',
  RESULTADOS_EVALUACION_DOCENTE = 'AMD_RESULTADOS_EVALUACION_DOCENTE',

  CURSO = 'AMD_CURSO',
  CURSO_CAMBIA_PERIODO = 'AMD_CURSO_CAMBIA_PERIODO',
  CURSO_INICIA_CLASE = 'AMD_CURSO_INICIA_CLASE',
  CURSO_TERMINA_CLASE = 'AMD_CURSO_TERMINA_CLASE',
  CURSO_CAMBIA_SALA = 'AMD_CURSO_CAMBIA_SALA',
  CURSO_SOPORTE_TI = 'AMD_CURSO_SOPORTE_TI',
  CURSO_SOPORTE_TI_SOLICITUD = 'AMD_CURSO_SOPORTE_TI_SOLICITUD',
  CURSO_ASISTENCIA = 'AMD_CURSO_ASISTENCIA',
  CURSO_GUARDA_ASISTENCIA = 'AMD_CURSO_GUARDA_ASISTENCIA',
  CURSO_EXCEPCION = 'AMD_CURSO_EXCEPCION',
  CURSO_ENVIA_EXCEPCION = 'AMD_CURSO_ENVIA_EXCEPCION',
  CURSO_APRENDIZAJES_ESPERADOS = 'AMD_CURSO_APRENDIZAJES_ESPERADOS',
  CURSO_GUARDA_APRENDIZAJES_ESPERADOS = 'AMD_CURSO_GUARDA_APRENDIZAJES_ESPERADOS',

  WIDGET_RIESGOS = 'AMD_WIDGET_RIESGOS',
  WIDGET_NOTAS = 'AMD_WIDGET_NOTAS',
  WIDGET_ASESOR = 'AMD_WIDGET_ASESOR',
  WIDGET_ASESOR_SOLICITUD = 'AMD_WIDGET_ASESOR_SOLICITUD',
  WIDGET_OPORTUNIDADES = 'AMD_WIDGET_OPORTUNIDADES',
  WIDGET_TIPO_ESTUDIANTES = 'AMD_WIDGET_TIPO_ESTUDIANTES',
  WIDGET_PREREQUISITOS = 'AMD_WIDGET_PREREQUISITOS',
  WIDGET_PERFIL_ESTUDIANTES = 'AMD_WIDGET_PERFIL_ESTUDIANTES',

  OBSERVACIONES = 'AMD_OBSERVACIONES',
  GUARDA_OBSERVACION = 'AMD_GUARDA_OBSERVACION',
  DESCRIPTOR = 'AMD_DESCRIPTOR',

  RECUPERACIONES = 'AMD_RECUPERACIONES',
  SOLICITA_RECUPERACION = 'AMD_SOLICITA_RECUPERACION',
  DETALLE_RECUPERACION = 'AMD_DETALLE_RECUPERACION',

  NOTAS = 'AMD_NOTAS',
  INGRESA_NOTAS = 'AMD_INGRESA_NOTAS',

  MENSAJES = 'AMD_MENSAJES',
  ENVIA_MENSAJE = 'AMD_ENVIA_MENSAJE'


};